config/routes.rb
Rails.application.routes.draw do

  resources :triggers

  get 'user_profile/index'

  root 'home#index'

  devise_for :users
  resources :devices do
    delete 'streams/delete' => 'devices#delete_streams'
  end

  namespace :v1 do
    post 'streams/new'
    get 'device/:id/streams' => 'streams#list', as: 'device_streams'
    get 'device/:id/streams/last' => 'streams#last', as: 'device_streams_last'
    get 'device/:id/streams/:date' => 'streams#list'
    get 'device/:id/streams/:date/:end_date' => 'streams#list'
  end

end

app/models/device.rb
class Device < ActiveRecord::Base
  has_many :streams
  has_many :triggers
  belongs_to :user

  before_create :generate_key

  scope :all_from_user, ->(curr_user) { where(user_id: curr_user) }

  private
    def generate_key
      self.key = loop do
        token = SecureRandom.urlsafe_base64
        break token unless Device.exists?(key: token)
      end
    end

end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_device, only: [:show, :edit, :update, :destroy]
  before_action :set_device_by_id, only: [:streams, :delete_streams]
  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all_from_user(current_user)
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)
    @device.user = current_user
    
    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    if @device.user.id == current_user.id
      @device.destroy
      respond_to do |format|
        format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      render status: :bad_request
    end
  end

  def delete_streams
    @device.streams.delete_all
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'All Streams have been deleted.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    def set_device_by_id
      @device = Device.find(params[:device_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:key, :name, :description)
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for @device, :html => { :class => "form-horizontal device" } do |f| %>

    <% if @device.errors.any? %>
      <div id="error_expl" class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title"><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h3>
        </div>
        <div class="panel-body">
          <ul>
          <% @device.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      </div>
    <% end %>

  <% if @device.key %>
    <div class="control-group">
      <%= f.label :key, :class => 'control-label' %>
      <div class="controls">
        <span><%= @device.key %></span>
      </div>
    </div>
  <% end %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
  </div>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            devices_path, :class => 'btn btn-default' %>

<% end %>

app/views/devices/edit.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/devices/index.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:key) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <th><%=t '.streams', :default => t("helpers.streams") %></th>
    </tr>
  </thead>
  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= link_to device.id, device_path(device) %></td>
        <td><%= device.name %></td>
        <td><%= device.description %></td>
        <td><%= device.key %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_device_path(device), :class => 'btn btn-default btn-xs' %>

          <%= button_to t('.destroy', :default => t("helpers.links.destroy")),
                      device_path(device),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
        <td>
          <%= link_to t('.show_all_streams', :default => t("helpers.streams.show_all_streams")),
                      v1_device_streams_path(device, token: device.user.token), :class => 'btn btn-default btn-xs', :target => "_blank" %>

          <%= link_to t('.show_last_streams', :default => t("helpers.streams.show_last_streams")),
                      v1_device_streams_last_path(device, token: device.user.token), :class => 'btn btn-default btn-xs', :target => "_blank" %>

          <%= button_to t('.destroy', :default => t("helpers.links.delete")),
                      device_streams_delete_path(device),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm_streams_delete", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-info' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_device_path,
            :class => 'btn btn-primary' %>

app/views/devices/new.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/devices/show.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:key) %>:</strong></dt>
  <dd><%= @device.key %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @device.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @device.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @device.user_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              devices_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_device_path(@device), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              device_path(@device),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>