config/routes.rb
Rails.application.routes.draw do

  resources :triggers

  get 'user_profile/index'

  root 'home#index'

  devise_for :users
  resources :devices do
    delete 'streams/delete' => 'devices#delete_streams'
  end

  namespace :v1 do
    post 'streams/new'
    get 'device/:id/streams' => 'streams#list', as: 'device_streams'
    get 'device/:id/streams/last' => 'streams#last', as: 'device_streams_last'
    get 'device/:id/streams/:date' => 'streams#list'
    get 'device/:id/streams/:date/:end_date' => 'streams#list'
  end

end

app/models/trigger.rb
class Trigger < ActiveRecord::Base
  belongs_to :device
end

app/controllers/triggers_controller.rb
class TriggersController < ApplicationController
  before_action :set_trigger, only: [:show, :edit, :update, :destroy]

  # GET /triggers
  # GET /triggers.json
  def index
    @triggers = Trigger.all
  end

  # GET /triggers/1
  # GET /triggers/1.json
  def show
  end

  # GET /triggers/new
  def new
    @trigger = Trigger.new
    @devices = Device.all_from_user(current_user).map { |device| [device.name, device.id] }
  end

  # GET /triggers/1/edit
  def edit
  end

  # POST /triggers
  # POST /triggers.json
  def create
    @trigger = Trigger.new(trigger_params)

    respond_to do |format|
      if @trigger.save
        format.html { redirect_to @trigger, notice: 'Trigger was successfully created.' }
        format.json { render :show, status: :created, location: @trigger }
      else
        format.html { render :new }
        format.json { render json: @trigger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /triggers/1
  # PATCH/PUT /triggers/1.json
  def update
    respond_to do |format|
      if @trigger.update(trigger_params)
        format.html { redirect_to @trigger, notice: 'Trigger was successfully updated.' }
        format.json { render :show, status: :ok, location: @trigger }
      else
        format.html { render :edit }
        format.json { render json: @trigger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /triggers/1
  # DELETE /triggers/1.json
  def destroy
    @trigger.destroy
    respond_to do |format|
      format.html { redirect_to triggers_url, notice: 'Trigger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trigger
      @trigger = Trigger.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trigger_params
      params.require(:trigger).permit(:device_id, :title, :email, :property, :operation, :value, :message)
    end
end

app/helpers/triggers_helper.rb
module TriggersHelper
end

app/views/triggers/_form.html.erb
<%= form_for(@trigger) do |f| %>
  <% if @trigger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trigger.errors.count, "error") %> prohibited this trigger from being saved:</h2>

      <ul>
      <% @trigger.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :device_id %><br>
    <%= select("trigger", "device_id", @devices) %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :property %><br>
    <%= f.text_field :property %>
  </div>
  <div class="field">
    <%= f.label :operation %><br>
    <%= f.text_field :operation %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/triggers/edit.html.erb
<h1>Editing trigger</h1>

<%= render 'form' %>

<%= link_to 'Show', @trigger %> |
<%= link_to 'Back', triggers_path %>

app/views/triggers/index.html.erb
<%- trigger = Trigger -%>

<div class="page-header">
  <h1><%=t '.title', :default => trigger.model_name.human.pluralize.titleize %></h1>
</div>

<% if @triggers.nil? %>
  <h2>
    ops, there's no triggers.
  </h2>
<% else %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>id</th>
      <th>From Device</th>
      <th>Title</th>
      <th>Email</th>
      <th>Property</th>
      <th>Operation</th>
      <th>Value</th>
      <th>Message</th>

      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @triggers.each do |trigger| %>
      <tr>
        <td><%= trigger.id %></td>
        <td><%= trigger.device.name %></td>
        <td><%= trigger.title %></td>
        <td><%= trigger.email %></td>
        <td><%= trigger.property %></td>
        <td><%= trigger.operation %></td>
        <td><%= trigger.value %></td>
        <td><%= trigger.message %></td>
        <td><%= link_to t('.show', :default => t("helpers.links.show")),
                      trigger_path(trigger), :class => 'btn btn-default btn-xs' %>
        </td>

        <td><%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_trigger_path(trigger), :class => 'btn btn-default btn-xs' %>
        </td>

        <td>
        <%= button_to t('.destroy', :default => t("helpers.links.delete")),
                      trigger_path(trigger),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-info' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% end %>
<%= link_to 'New Trigger', new_trigger_path %>

app/views/triggers/new.html.erb
<h1>New trigger</h1>

<%= render 'form' %>

<%= link_to 'Back', triggers_path %>

app/views/triggers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Device:</strong>
  <%= @trigger.device %>
</p>

<p>
  <strong>Title:</strong>
  <%= @trigger.title %>
</p>

<p>
  <strong>Email:</strong>
  <%= @trigger.email %>
</p>

<p>
  <strong>Property:</strong>
  <%= @trigger.property %>
</p>

<p>
  <strong>Operation:</strong>
  <%= @trigger.operation %>
</p>

<p>
  <strong>Value:</strong>
  <%= @trigger.value %>
</p>

<p>
  <strong>Message:</strong>
  <%= @trigger.message %>
</p>

<%= link_to 'Edit', edit_trigger_path(@trigger) %> |
<%= link_to 'Back', triggers_path %>