config/routes.rb
Rails.application.routes.draw do

  resources :triggers

  get 'user_profile/index'

  root 'home#index'

  devise_for :users
  resources :devices do
    delete 'streams/delete' => 'devices#delete_streams'
  end

  namespace :v1 do
    post 'streams/new'
    get 'device/:id/streams' => 'streams#list', as: 'device_streams'
    get 'device/:id/streams/last' => 'streams#last', as: 'device_streams_last'
    get 'device/:id/streams/:date' => 'streams#list'
    get 'device/:id/streams/:date/:end_date' => 'streams#list'
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    &copy; CI&amp;T 2014
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Doc", 'https://github.com/ciandt-dev/CIOT/wiki', :target => "_blank" %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">CIOT</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Devices", devices_path %></li>
        <li><%= link_to "Triggers", triggers_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "User Profile", :controller => :user_profile, :action => :index  %></li>
              <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
            </ul>
        <% else %>
          <li><%= link_to "Sign Up", new_registration_path(:user) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Log In <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <%= form_for(:user, url: user_session_path, :html => { :class => "login-dropdown" }) do |f| -%>
                <li>
                  <div class="control-group">
                    <%= f.label :login, :class => 'control-label' %>
                    <div class="controls">
                      <%= f.email_field :email, autofocus: true, :class => 'form-control' %>
                    </div>
                  </div>
                </li>
                <li>
                  <div class="control-group">
                    <%= f.label :password, :class => "control-label" %>
                    <div class="controls">
                      <%= f.password_field :password, :class => 'form-control' %>
                    </div>
                  </div>
                </li>
                <li>
                  <%= f.label :remember_me, :class => 'checkbox' do %>
                    <%= f.check_box :remember_me %>
                    Remember me
                  <% end %>
                </li>
                <li>
                  <%= f.submit "Sign in", :class => "btn btn-primary" %>
                </li>
              <% end -%>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "CIOT" %></title>
    <link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>

      <div class="row">
        <div class="col-lg-12">
          <%= render partial: "shared/flash_messages", flash: flash %>
          <%= yield %>
        </div>
      </div>

      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>